Property: module
openjs-foundation/package-json-research pull request #12
Opened 2024-08-23 20:56 UTC by rotu

Documented the top-level `module` entry point. I stopped short of prescriptive recommendations.

This field has been *very* confusing to me. On one hand, it's ubiquitous and just works for some tooling. On the other hand, it's undocumented by `npm`. I stopped short of it, but it would be nice if there were some official normative guidance for how to stop using this field without breaking things, now that `exports` seems a capable replacement.

2024-08-23 23:42 UTC, wesleytodd commented
Honestly laughed out loud a few times reading this, but this is a GREAT addition. It would be nice if we could get some folks from the bundlers to help with this so we can get a more clear answer on the future of this field.

2024-08-24 00:06 UTC, ljharb reviewed
Might also be worth noting that `eslint-plugin-import` supports it via `eslint-import-resolver-webpack`

2024-08-24 00:06 UTC, ljharb commented on research/module.md
> +In the meantime, bundlers converged around adding top-level field, with the most common being `module`, though this was never adopted by `node`.
predating module is `jsnext:main` which should also be documented and cross-linked

2024-08-24 00:06 UTC, ljharb commented on research/module.md
> +Where used by bundlers `module` is used in parallel with top-level `main`, `browser`, et al. These are collectively referred to as `mainFields`.[^2]
let's be sure this links to the browser field docs :-)

2024-08-24 03:13 UTC, rotu commented on research/module.md
> +Where used by bundlers `module` is used in parallel with top-level `main`, `browser`, et al. These are collectively referred to as `mainFields`.[^2]
I linked to the docs in `npm` but I think it was only documented there because there was no better "official" place to document it. It seems never used by `npm`.

2024-08-24 03:21 UTC, rotu commented
> Honestly laughed out loud a few times reading this, but this is a GREAT addition.

@wesleytodd I'm glad to be helpful, but I'm curious why you found it funny... Neither my wife nor my cat laughed when I forced them to listen to my drafts.

2024-08-24 03:21 UTC, ljharb commented on research/module.md
> +  - npm also [documents the `browser` top-level property](https://github.com/npm/cli/blob/e674987c8dc5634c3b2a8a4d0f024d15041ba23c/docs/lib/content/configuring-npm/package-json.md?plain=1#L354-L359).
it is not unused whatsoever; it's what browserify (the original and defining bundler) uses, and all bundlers i'm aware of use it: https://github.com/defunctzombie/package-browser-field-spec (and any that don't are broken)

2024-08-24 03:33 UTC, rotu commented on research/module.md
> +  - npm also [documents the `browser` top-level property](https://github.com/npm/cli/blob/e674987c8dc5634c3b2a8a4d0f024d15041ba23c/docs/lib/content/configuring-npm/package-json.md?plain=1#L354-L359).
Thanks! Yes, this was poorly worded and I will revise.

That said, I don't know what you linked. That repo has a lot of stars (438) but I don't know (and don't know how to determine) if it has any normative weight.

2024-08-24 03:35 UTC, ljharb commented on research/module.md
> +  - npm also [documents the `browser` top-level property](https://github.com/npm/cli/blob/e674987c8dc5634c3b2a8a4d0f024d15041ba23c/docs/lib/content/configuring-npm/package-json.md?plain=1#L354-L359).
That is indeed the original and standard specification for the field - closest to an official thing that can exist.

2024-08-24 04:12 UTC, rotu commented on research/module.md
> +  - npm also [documents the `browser` top-level property](https://github.com/npm/cli/blob/e674987c8dc5634c3b2a8a4d0f024d15041ba23c/docs/lib/content/configuring-npm/package-json.md?plain=1#L354-L359).
I believe you (and your edit mentioning browserify certainly helped clarify!)

That said, many proposals have been deprecated or lost traction, so it's hard to tell whether the spec was ever implemented as written and to what extent tools still match it!

2024-09-03 20:56 UTC, Ethan-Arrowood requested changes
this is looking great!

2024-09-03 20:56 UTC, Ethan-Arrowood commented on research/module.md
> +Historically, `main` has been the *only* way to declare a package's modules to Node. Node more recently supports the more flexible `exports`.
```suggestion
Historically, `main` has been the *only* way to declare a package's modules to Node.js. Node.js more recently supports the more flexible `exports`.
```

Nit: let's be consistent with using proper spelling and capitalization for names for things (i.e. npm, Node.js, GitHub)

2024-09-03 22:27 UTC, rotu commented
@Ethan-Arrowood
> Nit: let's be consistent with using proper spelling and capitalization for names for things (i.e. npm, Node.js, GitHub)

Agreed. Got opinions about what should be a footnote and what should be an inline link? (and what's just excessive and shouldn't even be linked?)

2024-09-05 14:48 UTC, wesleytodd approved these changes
Awesome work!! I dont have any feedback off hand, but am so excited to see this stuff starting to move forward. The whole ecosystem will be better off with this stuff documented.

2024-09-05 15:28 UTC, Ethan-Arrowood commented
No opinions on links - i like the idea of this being a living research document. We can make edits over time if patterns start to emerge. Less rules the better to encourage more and more contributions

2024-09-05 15:28 UTC, Ethan-Arrowood approved these changes

2024-09-05 15:28 UTC, merged

2026-05-23 21:30 UTC, nazmuhammadansarnaz91-art commented
Nice work for GitHub open JS foundation pull application for open work for  best option